# Generated by Django 5.2.7 on 2025-10-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portefeuille',
            name='frequence_contribution_recurrente',
        ),
    ]
