# Generated by Django 5.2.7 on 2025-10-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0002_remove_portefeuille_frequence_contribution_recurrente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portefeuille',
            old_name='montant_initialt_investissement',
            new_name='montant_initial_investissement',
        ),
    ]
