# Generated by Django 5.2.7 on 2025-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0003_rename_montant_initialt_investissement_portefeuille_montant_initial_investissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='choix_des_actifs',
            field=models.CharField(choices=[('ACTIONS', 'Actions'), ('OBLIGATIONS', 'Obligations'), ('ETF', 'ETF')], default='ACTIONS', max_length=100),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='frequence_contribution',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (2, 'Trimestrielle'), (3, 'Annuelle')], default=1),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='frais_gestion_annuels',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='etfs_populaires',
            field=models.ManyToManyField(blank=True, to='portefeuille.etf'),
        ),
    ]
