# Generated by Django 5.2.7 on 2025-10-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0004_etf_portefeuille_choix_des_actifs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='portefeuille',
            name='choix_des_actifs',
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='actifs',
            field=models.ManyToManyField(blank=True, to='portefeuille.actif'),
        ),
    ]
