# Generated by Django 5.2.7 on 2025-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0005_actif_remove_portefeuille_choix_des_actifs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actif',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Portefeuille',
        ),
    ]
